---
- hosts: localhost
  connection: local
  gather_facts: no

  vars:
    ansible_connection: local
    ansible_python_interpreter: "{{ansible_playbook_python}}"
  
  tasks:
    - name: Make sure homebrew bin is in path
      ansible.builtin.lineinfile:
        path: /etc/paths
        state: present
        line: '/opt/homebrew/bin'
      become: true
      become_user: root
      
    # If the user installs GNU sed through homebrew the path is different.
    - name: Register path to sed.
      command: which sed
      register: sed_which_result
      changed_when: false
      when: sed_path is undefined

    - name: Define sed_path variable.
      set_fact:
        sed_path: "{{ sed_which_result.stdout }}"
      when: sed_path is undefined

    # 
    - name: Register path to ZSH
      become: false
      local_action: command which zsh
      register: zsh_path

    - name: "Ensure homebrew zsh is in allowed shells"
      lineinfile:
        path: /etc/shells
        line: "{{ zsh_path.stdout }}"
      become: true

    # Homebrew
    - import_tasks: tasks/homebrew.yml
      #when: configure_terminal
      tags: ['terminal']
